export enum GameEvents {
    OnJoinNewGame = 'onJoinNewGame',
    OnJoinMultiplayerGame = 'onJoinMultiplayerGame',
    OnClick = 'onClick',
    OnLeave = 'onLeave',
    OnSecondPlayerJoined = 'onSecondPlayerJoined',
    UpdateDifferenceAmount = 'updateDifferenceAmount',
    OnProcessedClick = 'onProcessedClick',
    SendTime = 'sendTime',
    OnDefeat = 'onDefeat',
    OnVictory = 'onVictory',
    OnDeleteLevel = 'onDeleteLevel',
    OnGameSelection = 'onGameSelection',
    OnGameAccepted = 'onGameAccepted',
    OnGameRejected = 'onGameRejected',
    OnGameCancelledWhileWaitingForSecondPlayer = 'onGameCancelledWhileWaitingForSecondPlayer',
    OnGameCancelledWhileWaitingForAcceptation = 'onGameCancelledWhileWaitingForAcceptation',
    OnAbandonGame = 'onAbandonGame',
    OnStartCheatMode = 'onStartCheatMode',
    OnStopCheatMode = 'onStopCheatMode',

    UpdateSelection = 'updateSelection',
    InvalidName = 'invalidName',
    ToBeAccepted = 'toBeAccepted',
    PlayerSelection = 'playerSelection',
    RejectedGame = 'rejectedGame',
    StartClassicMultiplayerGame = 'startClassicMultiplayerGame',
    ShutDownGame = 'shutDownGame',
    DeleteLevel = 'deleteLevel',
    StartCheatMode = 'startCheatMode',
}
